import Head from 'next/head'
import Image from 'next/image'
import { Result } from '../interface/ssl-check-result'
import { getAllDomainCheckResult } from '../lib/api'
import { getBuildTime } from '../lib/util'
import styles from '../styles/Home.module.css'

type Props = {
  results: Array<Result>
  build_time: string
}

const Index = ({ results, build_time }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>チェック時刻: {build_time}</div>
        <div>
          {results.map((result) => (
            <div key={result.domain}>
              ドメイン: {result.domain}
              <br />
              結果: {result.isSsl ? 'SSL対応されています' : 'SSL対応されていません'}
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}

// ビルド時に実行される
export async function getStaticProps() {
  const results = await getAllDomainCheckResult();
  const build_time = getBuildTime();

  return {
    props: {
      results,
      build_time
    },
  }
}

export default Index
